FROM cassandra:2.2.4

MAINTAINER Vincenzo FERME <info@vincenzoferme.it>

# create the directory that is going to accomodate the app (data and configuration)
RUN mkdir -p /app
RUN mkdir -p /app/data
# just a reminder that the dump must be updated with https://github.com/benchflow/benchflow in case testing it is needed
COPY data/database.cql /app/data/database.cql

COPY bin/initialize-entrypoint.sh /app/initialize-entrypoint.sh
RUN chmod +x /app/initialize-entrypoint.sh

# copy custom configurations
COPY conf/cassandra.yaml /etc/cassandra/cassandra.yaml

ENTRYPOINT ["/app/initialize-entrypoint.sh"]

# it seems that if we override the entrypoint then wen also need to define again the default command
CMD ["cassandra","-f"]