FROM cassandra:2.2.4

# create the directory that is going to accomodate the app (data and configuration)
RUN mkdir -p /app/data
COPY data/database.cql /app/data

COPY bin/initialize-entrypoint.sh /app
RUN chmod +x /app/initialize-entrypoint.sh

ENTRYPOINT ["/app/initialize-entrypoint.sh"]

# it seems that if we override the entrypoint then wen also need to define again the default command
CMD ["cassandra","-f"]